-- Flyway 마이그레이션 파일명 규칙 샘플: V{번호}__{설명}.sql (08_개발표준 4절).
-- 실제 팀 스키마(users/faq/store/chat_session/chat_message 등, 06_ERD.dbml 기준)는 아직 ERD가
-- 확정되지 않아 여기 포함하지 않았다. 담당자가 확정 후 이 파일 하나로 pgvector 확장 +
-- 전체 테이블을 넣거나, 이 sample_item 마이그레이션을 대체하면 된다.

CREATE TABLE sample_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    content     TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP
);
